### ISSUE TITLE
INFOGRAFÍA_FASES DE GESTIÓN DE PROYECTOS DE SOFTWARE

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/infografia-Eva155-1#2]
[FASES DE GESTIÓN DE PROYECTOS DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Eva155-1/files/7113204/FASES.DE.GESTION.DE.PROYECTOS.DE.SOFTWARE.pdf)

**Comment by dulce-blm** [comment]
Calificación 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
